# CMake generated Testfile for 
# Source directory: U:/DEV/cmake-os2/Tests/CMakeLib
# Build directory: U:/DEV/cmake-os2/Tests/CMakeLib
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMakeLib.testArgumentParser "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testArgumentParser")
set_tests_properties(CMakeLib.testArgumentParser PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestBinPacker "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testCTestBinPacker")
set_tests_properties(CMakeLib.testCTestBinPacker PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceAllocator "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testCTestResourceAllocator")
set_tests_properties(CMakeLib.testCTestResourceAllocator PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceSpec "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testCTestResourceSpec" "U:/DEV/cmake-os2/Tests/CMakeLib")
set_tests_properties(CMakeLib.testCTestResourceSpec PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testCTestResourceGroups "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testCTestResourceGroups")
set_tests_properties(CMakeLib.testCTestResourceGroups PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testGeneratedFileStream "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testGeneratedFileStream")
set_tests_properties(CMakeLib.testGeneratedFileStream PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRST "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testRST" "U:/DEV/cmake-os2/Tests/CMakeLib")
set_tests_properties(CMakeLib.testRST PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testRange "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testRange")
set_tests_properties(CMakeLib.testRange PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testOptional "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testOptional")
set_tests_properties(CMakeLib.testOptional PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testString "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testString")
set_tests_properties(CMakeLib.testString PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testStringAlgorithms "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testStringAlgorithms")
set_tests_properties(CMakeLib.testStringAlgorithms PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testSystemTools "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testSystemTools")
set_tests_properties(CMakeLib.testSystemTools PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUTF8 "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testUTF8")
set_tests_properties(CMakeLib.testUTF8 PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLParser "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testXMLParser")
set_tests_properties(CMakeLib.testXMLParser PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testXMLSafe "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testXMLSafe")
set_tests_properties(CMakeLib.testXMLSafe PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testFindPackageCommand "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testFindPackageCommand")
set_tests_properties(CMakeLib.testFindPackageCommand PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVProcessChain "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testUVProcessChain" "U:/DEV/cmake-os2/Tests/CMakeLib/testUVProcessChainHelper.exe")
set_tests_properties(CMakeLib.testUVProcessChain PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVRAII "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testUVRAII")
set_tests_properties(CMakeLib.testUVRAII PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
add_test(CMakeLib.testUVStreambuf "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLibTests.exe" "testUVStreambuf" "U:/DEV/cmake-os2/bin/cmake.exe")
set_tests_properties(CMakeLib.testUVStreambuf PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;60;add_test;U:/DEV/cmake-os2/Tests/CMakeLib/CMakeLists.txt;0;")
subdirs("PseudoMemcheck")
