# CMake generated Testfile for 
# Source directory: U:/DEV/cmake-os2/Tests/CMakeTests
# Build directory: U:/DEV/cmake-os2/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(CMake.List "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/ListTest.cmake")
set_tests_properties(CMake.List PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;13;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.VariableWatch "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/VariableWatchTest.cmake")
set_tests_properties(CMake.VariableWatch PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Include "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/IncludeTest.cmake")
set_tests_properties(CMake.Include PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.FindBase "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/FindBaseTest.cmake")
set_tests_properties(CMake.FindBase PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Toolchain "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/ToolchainTest.cmake")
set_tests_properties(CMake.Toolchain PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.GetFilenameComponentRealpath "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
set_tests_properties(CMake.GetFilenameComponentRealpath PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Version "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/VersionTest.cmake")
set_tests_properties(CMake.Version PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Message "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/MessageTest.cmake")
set_tests_properties(CMake.Message PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.File "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/FileTest.cmake")
set_tests_properties(CMake.File PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.ImplicitLinkInfo "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
set_tests_properties(CMake.ImplicitLinkInfo PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.ModuleNotices "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/ModuleNoticesTest.cmake")
set_tests_properties(CMake.ModuleNotices PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.GetProperty "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/GetPropertyTest.cmake")
set_tests_properties(CMake.GetProperty PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.If "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/IfTest.cmake")
set_tests_properties(CMake.If PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.String "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/StringTest.cmake")
set_tests_properties(CMake.String PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.Math "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/MathTest.cmake")
set_tests_properties(CMake.Math PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.CMakeMinimumRequired "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
set_tests_properties(CMake.CMakeMinimumRequired PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.CompilerIdVendor "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/CompilerIdVendorTest.cmake")
set_tests_properties(CMake.CompilerIdVendor PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.ProcessorCount "U:/DEV/cmake-os2/bin/cmake" "-DKWSYS_TEST_EXE=U:/DEV/cmake-os2/Source/kwsys/cmsysTestsCxx.exe" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/ProcessorCountTest.cmake")
set_tests_properties(CMake.ProcessorCount PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.PushCheckState "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/PushCheckStateTest.cmake")
set_tests_properties(CMake.PushCheckState PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.While "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/WhileTest.cmake")
set_tests_properties(CMake.While PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.CMakeHostSystemInformation "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeHostSystemInformationTest.cmake")
set_tests_properties(CMake.CMakeHostSystemInformation PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;33;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.FileDownload "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/FileDownloadTest.cmake")
set_tests_properties(CMake.FileDownload PROPERTIES  PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum" _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;35;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.FileDownloadBadHash "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/FileDownloadBadHashTest.cmake")
set_tests_properties(CMake.FileDownloadBadHash PROPERTIES  WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;39;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.FileUpload "U:/DEV/cmake-os2/bin/cmake" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/FileUploadTest.cmake")
set_tests_properties(CMake.FileUpload PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;44;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.EndStuff "U:/DEV/cmake-os2/bin/cmake" "-Ddir:STRING=U:/DEV/cmake-os2/Tests/CMakeTests/EndStuffTest" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/EndStuffTest.cmake")
set_tests_properties(CMake.EndStuff PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;53;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.GetPrerequisites "U:/DEV/cmake-os2/bin/cmake" "-DConfiguration:STRING=" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/GetPrerequisitesTest.cmake")
set_tests_properties(CMake.GetPrerequisites PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;55;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.PolicyCheck "U:/DEV/cmake-os2/bin/cmake" "-DCMake_BINARY_DIR:PATH=U:/DEV/cmake-os2" "-DCMake_SOURCE_DIR:PATH=U:/DEV/cmake-os2" "-DGIT_EXECUTABLE:STRING=E:/USR/BIN/git.exe" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/PolicyCheckTest.cmake")
set_tests_properties(CMake.PolicyCheck PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;63;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
add_test(CMake.CheckSourceTree "U:/DEV/cmake-os2/bin/cmake" "-DCMake_BINARY_DIR:PATH=U:/DEV/cmake-os2" "-DCMake_SOURCE_DIR:PATH=U:/DEV/cmake-os2" "-DGIT_EXECUTABLE:STRING=E:/USR/BIN/git.exe" "-DHOME:STRING=C:/Home" "-P" "U:/DEV/cmake-os2/Tests/CMakeTests/CheckSourceTreeTest.cmake")
set_tests_properties(CMake.CheckSourceTree PROPERTIES  _BACKTRACE_TRIPLES "U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;7;add_test;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;78;AddCMakeTest;U:/DEV/cmake-os2/Tests/CMakeTests/CMakeLists.txt;0;")
